version: '3.8'

services:
  web:
    build: .
    ports:
      - "${SERVICE_PORT:-5000}:5000"
    volumes:
      - uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - APP_PASSWORD=${APP_PASSWORD:-simplepassword}

volumes:
  uploads:
    driver: local

